### ISSUE TITLE
Multiple Skills Sets

### ISSUE THREAD

**Issue by j3ffb** [RoyalVeterinaryCollege/Folium#1]
We need to cater for a user being able to view more than one Skill Set.

Currently only the first Skill Set is used, there is no way to change this, Skill Sets that are assigned to users take priority over 'self assignable' ones (Sets which in theory anyone can use). If a user logs in who doesn't have a Skill Set they automatically use the first self assignable one.

A Skill Set represents a collection of skills. A course can have multiple Skill Sets, which could be different versions of the same set of skills. A user is assigned to a Skill Set, often via their course enrolment. They continue to use this version of the Skill Set throughout their course.

I propose that we introduce a new screen (accessible from their profile image menu) for a users to see which Skill Sets they are associated with and also allow them to enrol in other Sets which are setup as self assignable. If a user logs in with no Skill Sets then they are automatically taken to this screen.
We will then need to provide a Skill Set selection drop down on the Skills screen and also before the user first associates any skills with an Entry. Once a user has chosen the Skill Set to associate with an entry it cannot be changed.

**Comment by peternunn** [comment]
As per previous comments. 

- add-skills-set-01.jpg - profile editor selected, BVetMed Day One Skills automatically assigned to user.  User follows Add Skill Set button (not sure if this should be a link)
![add-skills-set-01](https://user-images.githubusercontent.com/5220918/29871279-14afad44-8d83-11e7-9ec7-be03adaaa210.jpg)

- add-skills-set-02.jpg - Add Skill Set window. Lists all Skill Sets available. In the example BVetMed Day One Skills is automatically associated. UKPSF is chosen. Add button selected.
![add-skills-set-02](https://user-images.githubusercontent.com/5220918/29871438-a09385f6-8d83-11e7-9330-129b1324f189.jpg)

- add-skills-set-02.jpg - UKPSF appears in Skill Sets list. A remove link is provided. User selects the Save button to add the UKPSF Skills Set to list
![add-skills-set-03](https://user-images.githubusercontent.com/5220918/29871526-f90778e6-8d83-11e7-980e-16349004d3f4.jpg)

**Comment by peternunn** [comment]
Swapping Skills -

- skills-type-swap-01.jpg When a user is associated with more than one sills list the skills list is displayed in the secondary row. A swap icon is added so that the Skills List can be swapped. The user had selected the swap icon:
![skills-type-swap-01](https://user-images.githubusercontent.com/5220918/29873537-8ab72aaa-8d8b-11e7-9484-a1d69007e9d7.jpg)
skills-type-swap-02.jpg - A model widow displays the Skill Sets available. In the example, BVetMed skills are swapped for UKPSF
![skills-type-swap-02](https://user-images.githubusercontent.com/5220918/29873653-f0fc93ae-8d8b-11e7-9518-03115d8a2b8d.jpg)
skills-type-swap-03.jpg - Skill set is swapped to UKPSF and displayed
![skills-type-swap-03](https://user-images.githubusercontent.com/5220918/29873918-f201937a-8d8c-11e7-8d4f-8aa6883f71ca.jpg)

**Comment by peternunn** [comment]
Phone version for swapping skills: Note that when skills are able to be swapped the search becomes an icon link, and the name of the skills is not visible.
![skills-swap--phone-01](https://user-images.githubusercontent.com/5220918/29875279-68e844c6-8d91-11e7-8d8a-0c9893c4d705.jpg)
![skills-swap--phone-02](https://user-images.githubusercontent.com/5220918/29875284-6ca561b6-8d91-11e7-9b7e-145c0128ab65.jpg)
![skills-swap--phone-03](https://user-images.githubusercontent.com/5220918/29875288-6ff8a86e-8d91-11e7-9c2f-69000a061169.jpg)

**Comment by j3ffb** [comment]
This work has been completed
